### ISSUE TITLE
Setup image processor

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/kafka-image-processor#11]
- [x] Setup SBT to run the processor hooks (maybe instantiate class manually instead of using dependency injection on the main method)
- [x] Add binding to kafka topic, print to console that it's receiving them
- [x] Add WS play to fetch images from the url, republish to kafka topic
- [x] Add 2nd processor to listen to downloaded images, run processing to apply filter to images
- [ ] Push image binary to kafka so it can be downloaded by the frontend

**Comment by inakianduaga** [comment]
We might have to switch clients to a kafka stream because the current one doesn't seeem to poll properly?
https://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/

**Comment by inakianduaga** [comment]
#### Check published topics through cli quickly

```
docker run --rm -it --link kafka --network kafkaplayground_default ryane/kafkacat -C -b 172.17.0.1:9092 -t Images.Urls
```

**Comment by inakianduaga** [comment]
# TODO:

images fail to be pushed, try

- [ ] Pushing a test payload instead of the actual image
- [ ] Check if maybe the pushing gets messed up by the next cycle since the fetch is async
- [ ] If we can't get it to work maybe we should swtich to Kafka streams
