### ISSUE TITLE
Improve websocket-Akka integration

### ISSUE THREAD

**Issue by inakianduaga** [inakianduaga/kafka-image-processor#3]
Play 2.5 changed a few things,

- [ ] Use dependency injection of the actor system

https://www.playframework.com/documentation/2.5.x/ScalaWebSockets

- [x] Remove random websocket id  / actor mapping, we don't need it, we'll use the actor's own path as the unique identifier to be able to recognize it. 

- [ ] Add custom JSON data types for the InEvent / OutEvents

**Comment by inakianduaga** [comment]
# TODO:
- [ ] See if we can inject the actor system into the object companion? (method injection??)

**Comment by inakianduaga** [comment]
# Websockets in play

How to handle different message types in one websocket
https://anadea.info/blog/websockets-in-play-framework
